export BlockRender from './block-render';
export caretPosition from './caret-position';
export getCurrentBlocks from './get-current-blocks';
export getCurrentFormats from './get-current-formats';
export isBlockActive from './is-block-active';
export isFormatActive from './is-format-active';
export mergeDefaultData from './merge-default-data';
export setSelection from './set-selection';
export { applyFormat, removeFormat, updateFormat, toggleFormat } from './handle-format';
export { setBlockData, createBlock, removeBlock, getBlock, transformBlock } from './handle-block';
